### ISSUE TITLE
onChange is not working

### ISSUE THREAD

**Issue by norbajunior** [ajoslin/react-credit-card-primitives#4]
Hey @ajoslin! First of all, thanks for the lib.

I tried to run the example code on README but the onChange callback didn't work.

Is there something wrong in the example? I'm trying to use it to get the card type.

Thank you.

**Comment by ajoslin** [comment]
The example might be outdated.. I will move the example to codesandbox.com and see.

**Comment by ajoslin** [comment]
https://codesandbox.io/s/5zk2p8rl3l

Open the console and it works.

**Comment by norbajunior** [comment]
thanks @ajoslin I'll take a look.

**Comment by ajoslin** [comment]
No problem. I'll go ahead and close this, please reopen if you see something not working.
